/**
 * GENERATED by scripts/writeBuildInfo.ts (npm prebuild) — DO NOT EDIT BY HAND.
 * Regenerated on every `npm run build` from `git rev-parse` and a real `vitest run`.
 */
export const BUILD_INFO = {
  commit: 'a4cf706',
  testsPassing: 111,
  testsTotal: 111,
  verifiedAt: '2026-07-18',
} as const;
