/**
 * GENERATED by scripts/writeBuildInfo.ts (npm prebuild) — DO NOT EDIT BY HAND.
 * Regenerated on every `npm run build` from `git rev-parse` and a real `vitest run`.
 */
export const BUILD_INFO = {
  commit: '2fed53d',
  testsPassing: 137,
  testsTotal: 137,
  verifiedAt: '2026-08-29',
} as const;
