/**
 * Build-provenance generator — runs as `prebuild` (automatically before every `vite build`,
 * locally and in the deploy workflow). Writes src/ui/buildInfo.ts from LIVE sources:
 *   - commit hash:  `git rev-parse --short HEAD` (never typed by hand)
 *   - test counts:  an actual `vitest run --reporter=json` execution, parsed
 *   - verifiedAt:   the date of THIS run
 * Same principle as ε_impl in Phase A: computed each run, never a stale copy. The generated
 * module is committed so `npm run dev` works without a build, but every production build
 * regenerates it — the deployed footer can only show numbers that were true at build time.
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const commit = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim();

// Run the real test suite with the JSON reporter and parse the actual counts.
const tmp = join(root, 'node_modules', '.vitest-buildinfo.json');
execSync(`npx vitest run --reporter=json --outputFile="${tmp}"`, { cwd: root, stdio: 'ignore' });
const results = JSON.parse(readFileSync(tmp, 'utf8')) as {
  numTotalTests: number;
  numPassedTests: number;
  success: boolean;
};
rmSync(tmp, { force: true });

if (!results.success) {
  console.error(`writeBuildInfo: test suite FAILED (${results.numPassedTests}/${results.numTotalTests}) — refusing to stamp a green footer.`);
  process.exit(1);
}

const verifiedAt = new Date().toISOString().slice(0, 10);
const out = `/**
 * GENERATED by scripts/writeBuildInfo.ts (npm prebuild) — DO NOT EDIT BY HAND.
 * Regenerated on every \`npm run build\` from \`git rev-parse\` and a real \`vitest run\`.
 */
export const BUILD_INFO = {
  commit: '${commit}',
  testsPassing: ${results.numPassedTests},
  testsTotal: ${results.numTotalTests},
  verifiedAt: '${verifiedAt}',
} as const;
`;
writeFileSync(join(root, 'src', 'ui', 'buildInfo.ts'), out, 'utf8');
console.log(`buildInfo.ts written: ${commit} · ${results.numPassedTests}/${results.numTotalTests} tests · ${verifiedAt}`);
